name: container

on:
  push:
    branches:
      - main
    paths:
      - frontend
  workflow_dispatch: #Manual trigger option

defaults:
  run:
    working-directory: frontend

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # This variable tells Husky to skip the install process
      HUSKY_SKIP: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install packages dependencies
        run: npm install

      - name: Format the files
        run: npm run format

      - name: Checking the lint of the Package
        run: npx run lint
        
      - name: Run the test cases  
        run: npm run test

      - name: Run the test coverage
        run: npm run test:cov

