name: container

on:
  push:
    branches:
      - main
    paths:
      - frontend
  workflow_dispatch: #Manual trigger option

defaults:
  run:
    working-directory: frontend

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test
      - run: npm run test:cov
      - run: npm run build
