name: container

on:
  push:
    branches:
      - main
    paths:
      - frontend
  workflow_dispatch: #Manual trigger option

defaults:
  run:
    working-directory: frontend

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # This variable tells Husky to skip the install process
      HUSKY: 0

    steps:
      - uses: actions/checkout@v3
      - run: npm run install
      - run: npx run lint
      - run: npm run test
